#!/usr/bin/env python
import sys
from subprocess import check_call
from shutil import rmtree
from os import path

from igor.project_parser import ProjectParser

if len(sys.argv) < 2:
    print("Needs a repository path")
    sys.exit(1)

git_repository = sys.argv[1]

tmp_path = "/tmp/igor.git"

if path.exists(tmp_path):
    rmtree(tmp_path)

cmd = ["git", "clone", "-q", "--depth", "1", git_repository, tmp_path]
check_call(cmd)

p = ProjectParser(tmp_path).write()
rmtree(tmp_path)
